use_frameworks!

platform :ios, '9.0'

target 'HModuleBCategory_Example' do
  pod 'HModuleBCategory', :path => '../'

  target 'HModuleBCategory_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
